version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: film
      POSTGRES_PASSWORD: film
      POSTGRES_DB: filmdb
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://film:film@db:5432/filmdb
    ports:
      - "8000:8000"
volumes:
  db-data:
