[project]
name = "filmtracker-api"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlmodel",
    "alembic"
    ,"uuid6"
    ,"psycopg2-binary"
]

[project.optional-dependencies]
test = ["pytest", "httpx"]
